---
- hosts: all
  become: True

  vars:
    tomcat_version: 8.5.23

    tomcat_permissions_production: True

    tomcat_users:
      - username: "tomcat-user"
        password: "zippyops"
        roles: " tomcat,admin,manager,manager-gui"
  roles:
    - role: zaxos.tomcat-ansible-role
    
    
